"""
SupportPilot knowledge article schema.

This module defines the required structure for every learning article,
whether it is written manually or generated by an AI provider.
"""

from copy import deepcopy


ARTICLE_SCHEMA_VERSION = "1.0"


ARTICLE_TEMPLATE = {
    "schema_version": ARTICLE_SCHEMA_VERSION,
    "id": "",
    "title": "",
    "category": "",
    "difficulty": "Beginner",
    "estimated_time": "",
    "overview": "",
    "checklist": [],
    "common_indicators": [],
    "commands": [],
    "related_topics": [],
    "quiz": [],
    "sources": [],
    "generation": {
        "provider": None,
        "model": None,
        "generated_at": None,
    },
    "review": {
        "status": "draft",
        "reviewed_by": None,
        "reviewed_at": None,
        "notes": [],
    },
}


REQUIRED_TOP_LEVEL_FIELDS = {
    "schema_version",
    "id",
    "title",
    "category",
    "difficulty",
    "estimated_time",
    "overview",
    "checklist",
    "common_indicators",
    "commands",
    "related_topics",
    "quiz",
    "sources",
    "generation",
    "review",
}


VALID_DIFFICULTIES = {
    "Beginner",
    "Intermediate",
    "Advanced",
}


VALID_REVIEW_STATUSES = {
    "draft",
    "pending_review",
    "approved",
    "rejected",
}


def create_article_template() -> dict:
    """
    Return a new independent copy of the article template.

    Using deepcopy prevents one article from accidentally changing
    the shared template or another article.
    """

    return deepcopy(ARTICLE_TEMPLATE)