"""
Purpose:
    Provide a local deterministic article generator.

Responsibilities:
    - Generate a valid SupportPilot draft without using an external API.
    - Provide predictable offline behavior.
    - Support provider routing and automated tests.

Does NOT:
    - Call Gemini.
    - Call OpenAI.
    - Research technical sources.
    - Publish articles.
"""

from datetime import datetime, timezone
from typing import Any

from app.knowledge.article_schema import create_article_template
from app.knowledge.providers.base_provider import (
    BaseProvider,
    ProviderResult,
)


class FallbackProvider(BaseProvider):
    """
    Generate a structurally valid article using local template content.

    This provider is the final option in the provider chain. It prevents
    article generation from failing completely when external providers
    are unavailable.
    """

    @property
    def provider_name(self) -> str:
        """
        Return the stable provider identifier.
        """

        return "fallback"

    @property
    def model_name(self) -> str:
        """
        Return the local generation strategy name.
        """

        return "deterministic-template-v1"

    def is_configured(self) -> bool:
        """
        Return True because the fallback provider needs no API key.
        """

        return True

    def generate_article(
        self,
        prompt: str,
    ) -> ProviderResult:
        """
        Generate a local draft article.

        Args:
            prompt:
                Generation instructions. The fallback provider stores
                the prompt for diagnostics but does not interpret it.

        Returns:
            ProviderResult:
                A successful result containing a valid draft article.
        """

        article = self._create_fallback_article()

        metadata: dict[str, Any] = {
            "prompt_received": bool(prompt.strip()),
            "generation_mode": "offline",
            "requires_human_completion": True,
        }

        return ProviderResult(
            provider_name=self.provider_name,
            model_name=self.model_name,
            content=article,
            success=True,
            metadata=metadata,
        )

    def _create_fallback_article(self) -> dict[str, Any]:
        """
        Create a valid placeholder article.

        Returns:
            dict:
                A complete SupportPilot article that passes structural
                validation but clearly requires human completion.
        """

        generated_at = datetime.now(timezone.utc).isoformat()

        article = create_article_template()

        article["id"] = "generated-article-placeholder"
        article["title"] = "Generated Article Placeholder"
        article["category"] = "Uncategorized"
        article["difficulty"] = "Beginner"
        article["estimated_time"] = "To be determined"

        article["overview"] = (
            "External AI providers were unavailable. This draft was "
            "created locally and requires human completion before use."
        )

        article["checklist"] = [
            "Replace this placeholder with verified troubleshooting steps.",
            "Add technically accurate commands when applicable.",
            "Add trusted sources.",
            "Review the quiz before approval.",
        ]

        article["common_indicators"] = [
            "The requested article could not be generated externally.",
            "This article contains placeholder content.",
        ]

        article["commands"] = []

        article["related_topics"] = [
            "Manual article review",
            "Knowledge article authoring",
        ]

        article["quiz"] = [
            {
                "question": (
                    "What must happen before this placeholder article "
                    "can be approved?"
                ),
                "answers": [
                    "A human must review and complete it",
                    "It must be published automatically",
                    "The validator must be disabled",
                ],
                "correct_answer": (
                    "A human must review and complete it"
                ),
            }
        ]

        article["sources"] = []

        article["generation"] = {
            "provider": self.provider_name,
            "model": self.model_name,
            "generated_at": generated_at,
        }

        article["review"] = {
            "status": "draft",
            "reviewed_by": None,
            "reviewed_at": None,
            "notes": [
                "Generated by the local fallback provider.",
                "Technical content requires human completion.",
            ],
        }

        return article